import os

base_dir = '/Users/abydahana/Sites/aksara/themes/default/views/home'
default_index = os.path.join(base_dir, 'index.php')

with open(default_index, 'r', encoding='utf-8') as f:
    source = f.read()

# All translatable strings in the default English template (exact match)
# Format: { lang_code: { 'EN original': 'Translated' } }
translations = {
    'en-pir': {
        'GET STARTED': "SET SAIL",
        'Trusted by Organizations and Enterprises': "Trusted by the Seven Seas",
        'Community &amp; Engagement': "Crews &amp; Parleys",
        'Daily Visits': "Daily Loot",
        'Unique visitors today.': "Landlubbers spotted today.",
        'Weekly Visits': "Weekly Booty",
        'Total visits this week.': "Plunder this week.",
        'Monthly Visits': "Monthly Treasures",
        'Total visits this month.': "Treasure this month.",
        'Yearly Visits': "Yearly Gold",
        'Total visits this year.': "Gold this year.",
        'Published Articles': "Scrolls Penned",
        'Total content available.': "Scrolls in the hold.",
        'Interactions': "Rumors &amp; Murmurs",
        'User comments &amp; feedback.': "Whispers from the crew.",
        'Featured Galleries': "Treasured Maps",
        'See all galleries': "See all maps",
        'Latest news': "Latest Tales",
        'See all news': "See all tales",
        'Build Your Application Today': "Forge Yer Vessel Today",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Grab the charts of <strong>Aksara CMS</strong> and start buildin&#39; yer own ship without chains.",
        'GET SOURCE CODE': "GRAB THE CHARTS",
        'alt="Gallery"': 'alt="Treasure"',
        'alt="Map Interface"': 'alt="Treasure Map"',
        'alt="Blog"': 'alt="Scroll"',
    },
    'es': {
        'GET STARTED': "EMPEZAR",
        'Trusted by Organizations and Enterprises': "Con la confianza de organizaciones y empresas",
        'Community &amp; Engagement': "Comunidad e Interacción",
        'Daily Visits': "Visitas Diarias",
        'Unique visitors today.': "Visitantes únicos hoy.",
        'Weekly Visits': "Visitas Semanales",
        'Total visits this week.': "Total de visitas esta semana.",
        'Monthly Visits': "Visitas Mensuales",
        'Total visits this month.': "Total de visitas este mes.",
        'Yearly Visits': "Visitas Anuales",
        'Total visits this year.': "Total de visitas este año.",
        'Published Articles': "Artículos Publicados",
        'Total content available.': "Contenido total disponible.",
        'Interactions': "Interacciones",
        'User comments &amp; feedback.': "Comentarios y opiniones de usuarios.",
        'Featured Galleries': "Galerías Destacadas",
        'See all galleries': "Ver todas las galerías",
        'Latest news': "Últimas Noticias",
        'See all news': "Ver todas las noticias",
        'Build Your Application Today': "Construye tu Aplicación Hoy",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Obtén el código fuente completo de <strong>Aksara CMS</strong> y comienza a construir tu propia plataforma sin limitaciones.",
        'GET SOURCE CODE': "OBTENER CÓDIGO FUENTE",
    },
    'fr': {
        'GET STARTED': "COMMENCER",
        'Trusted by Organizations and Enterprises': "Approuvé par les organisations et entreprises",
        'Community &amp; Engagement': "Communauté et Engagement",
        'Daily Visits': "Visites Quotidiennes",
        'Unique visitors today.': "Visiteurs uniques aujourd'hui.",
        'Weekly Visits': "Visites Hebdomadaires",
        'Total visits this week.': "Total des visites cette semaine.",
        'Monthly Visits': "Visites Mensuelles",
        'Total visits this month.': "Total des visites ce mois.",
        'Yearly Visits': "Visites Annuelles",
        'Total visits this year.': "Total des visites cette année.",
        'Published Articles': "Articles Publiés",
        'Total content available.': "Contenu total disponible.",
        'Interactions': "Interactions",
        'User comments &amp; feedback.': "Commentaires et retours des utilisateurs.",
        'Featured Galleries': "Galeries en Vedette",
        'See all galleries': "Voir toutes les galeries",
        'Latest news': "Dernières Actualités",
        'See all news': "Voir toutes les actualités",
        'Build Your Application Today': "Construisez Votre Application Aujourd'hui",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Obtenez le code source complet d'<strong>Aksara CMS</strong> et commencez à construire votre propre plateforme sans limitations.",
        'GET SOURCE CODE': "OBTENIR LE CODE SOURCE",
    },
    'de': {
        'GET STARTED': "LOSLEGEN",
        'Trusted by Organizations and Enterprises': "Vertrauen von Organisationen und Unternehmen",
        'Community &amp; Engagement': "Community und Engagement",
        'Daily Visits': "Tägliche Besuche",
        'Unique visitors today.': "Einzigartige Besucher heute.",
        'Weekly Visits': "Wöchentliche Besuche",
        'Total visits this week.': "Gesamtbesuche diese Woche.",
        'Monthly Visits': "Monatliche Besuche",
        'Total visits this month.': "Gesamtbesuche diesen Monat.",
        'Yearly Visits': "Jährliche Besuche",
        'Total visits this year.': "Gesamtbesuche dieses Jahr.",
        'Published Articles': "Veröffentlichte Artikel",
        'Total content available.': "Gesamter verfügbarer Inhalt.",
        'Interactions': "Interaktionen",
        'User comments &amp; feedback.': "Benutzerkommentare und Feedback.",
        'Featured Galleries': "Ausgewählte Galerien",
        'See all galleries': "Alle Galerien ansehen",
        'Latest news': "Neueste Nachrichten",
        'See all news': "Alle Nachrichten ansehen",
        'Build Your Application Today': "Erstellen Sie Ihre Anwendung Heute",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Holen Sie sich den vollständigen Quellcode von <strong>Aksara CMS</strong> und bauen Sie Ihre eigene Plattform ohne Einschränkungen.",
        'GET SOURCE CODE': "QUELLCODE ERHALTEN",
    },
    'it': {
        'GET STARTED': "INIZIA",
        'Trusted by Organizations and Enterprises': "Fiducia da organizzazioni e imprese",
        'Community &amp; Engagement': "Comunità e Coinvolgimento",
        'Daily Visits': "Visite Giornaliere",
        'Unique visitors today.': "Visitatori unici oggi.",
        'Weekly Visits': "Visite Settimanali",
        'Total visits this week.': "Visite totali questa settimana.",
        'Monthly Visits': "Visite Mensili",
        'Total visits this month.': "Visite totali questo mese.",
        'Yearly Visits': "Visite Annuali",
        'Total visits this year.': "Visite totali quest'anno.",
        'Published Articles': "Articoli Pubblicati",
        'Total content available.': "Contenuto totale disponibile.",
        'Interactions': "Interazioni",
        'User comments &amp; feedback.': "Commenti e feedback degli utenti.",
        'Featured Galleries': "Gallerie in Evidenza",
        'See all galleries': "Vedi tutte le gallerie",
        'Latest news': "Ultime Notizie",
        'See all news': "Vedi tutte le notizie",
        'Build Your Application Today': "Costruisci la Tua Applicazione Oggi",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Ottieni il codice sorgente completo di <strong>Aksara CMS</strong> e inizia a costruire la tua piattaforma senza limitazioni.",
        'GET SOURCE CODE': "OTTIENI IL CODICE SORGENTE",
    },
    'pt': {
        'GET STARTED': "COMEÇAR",
        'Trusted by Organizations and Enterprises': "Confiado por organizações e empresas",
        'Community &amp; Engagement': "Comunidade e Engajamento",
        'Daily Visits': "Visitas Diárias",
        'Unique visitors today.': "Visitantes únicos hoje.",
        'Weekly Visits': "Visitas Semanais",
        'Total visits this week.': "Total de visitas esta semana.",
        'Monthly Visits': "Visitas Mensais",
        'Total visits this month.': "Total de visitas este mês.",
        'Yearly Visits': "Visitas Anuais",
        'Total visits this year.': "Total de visitas este ano.",
        'Published Articles': "Artigos Publicados",
        'Total content available.': "Conteúdo total disponível.",
        'Interactions': "Interações",
        'User comments &amp; feedback.': "Comentários e feedback dos usuários.",
        'Featured Galleries': "Galerias em Destaque",
        'See all galleries': "Ver todas as galerias",
        'Latest news': "Últimas Notícias",
        'See all news': "Ver todas as notícias",
        'Build Your Application Today': "Construa Sua Aplicação Hoje",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Obtenha o código-fonte completo do <strong>Aksara CMS</strong> e comece a construir sua própria plataforma sem limitações.",
        'GET SOURCE CODE': "OBTER CÓDIGO FONTE",
    },
    'ms': {
        'GET STARTED': "MULAKAN",
        'Trusted by Organizations and Enterprises': "Dipercayai oleh Organisasi dan Perusahaan",
        'Community &amp; Engagement': "Komuniti &amp; Penglibatan",
        'Daily Visits': "Kunjungan Harian",
        'Unique visitors today.': "Pelawat unik hari ini.",
        'Weekly Visits': "Kunjungan Mingguan",
        'Total visits this week.': "Jumlah kunjungan minggu ini.",
        'Monthly Visits': "Kunjungan Bulanan",
        'Total visits this month.': "Jumlah kunjungan bulan ini.",
        'Yearly Visits': "Kunjungan Tahunan",
        'Total visits this year.': "Jumlah kunjungan tahun ini.",
        'Published Articles': "Artikel Diterbitkan",
        'Total content available.': "Jumlah kandungan tersedia.",
        'Interactions': "Interaksi",
        'User comments &amp; feedback.': "Komen dan maklum balas pengguna.",
        'Featured Galleries': "Galeri Pilihan",
        'See all galleries': "Lihat semua galeri",
        'Latest news': "Berita Terkini",
        'See all news': "Lihat semua berita",
        'Build Your Application Today': "Bina Aplikasi Anda Hari Ini",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Dapatkan kod sumber lengkap <strong>Aksara CMS</strong> dan mula bina platform anda sendiri tanpa sekatan.",
        'GET SOURCE CODE': "DAPATKAN KOD SUMBER",
    },
    'tr': {
        'GET STARTED': "BAŞLAYIN",
        'Trusted by Organizations and Enterprises': "Kuruluşlar ve İşletmeler Tarafından Güvenilen",
        'Community &amp; Engagement': "Topluluk ve Katılım",
        'Daily Visits': "Günlük Ziyaretler",
        'Unique visitors today.': "Bugün benzersiz ziyaretçiler.",
        'Weekly Visits': "Haftalık Ziyaretler",
        'Total visits this week.': "Bu haftaki toplam ziyaretler.",
        'Monthly Visits': "Aylık Ziyaretler",
        'Total visits this month.': "Bu ayki toplam ziyaretler.",
        'Yearly Visits': "Yıllık Ziyaretler",
        'Total visits this year.': "Bu yılki toplam ziyaretler.",
        'Published Articles': "Yayınlanan Makaleler",
        'Total content available.': "Toplam mevcut içerik.",
        'Interactions': "Etkileşimler",
        'User comments &amp; feedback.': "Kullanıcı yorumları ve geri bildirimi.",
        'Featured Galleries': "Öne Çıkan Galeriler",
        'See all galleries': "Tüm galerileri gör",
        'Latest news': "Son Haberler",
        'See all news': "Tüm haberleri gör",
        'Build Your Application Today': "Uygulamanızı Bugün Oluşturun",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "<strong>Aksara CMS</strong>'nin tam kaynak kodunu alın ve kendi platformunuzu sınır olmaksızın oluşturmaya başlayın.",
        'GET SOURCE CODE': "KAYNAK KODU AL",
    },
    'vi': {
        'GET STARTED': "BẮT ĐẦU",
        'Trusted by Organizations and Enterprises': "Được tin dùng bởi các tổ chức và doanh nghiệp",
        'Community &amp; Engagement': "Cộng đồng &amp; Gắn kết",
        'Daily Visits': "Lượt truy cập hàng ngày",
        'Unique visitors today.': "Khách truy cập duy nhất hôm nay.",
        'Weekly Visits': "Lượt truy cập hàng tuần",
        'Total visits this week.': "Tổng lượt truy cập tuần này.",
        'Monthly Visits': "Lượt truy cập hàng tháng",
        'Total visits this month.': "Tổng lượt truy cập tháng này.",
        'Yearly Visits': "Lượt truy cập hàng năm",
        'Total visits this year.': "Tổng lượt truy cập năm nay.",
        'Published Articles': "Bài viết đã xuất bản",
        'Total content available.': "Tổng nội dung có sẵn.",
        'Interactions': "Tương tác",
        'User comments &amp; feedback.': "Bình luận và phản hồi của người dùng.",
        'Featured Galleries': "Thư viện nổi bật",
        'See all galleries': "Xem tất cả thư viện",
        'Latest news': "Tin tức mới nhất",
        'See all news': "Xem tất cả tin tức",
        'Build Your Application Today': "Xây dựng ứng dụng của bạn ngay hôm nay",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "Nhận mã nguồn đầy đủ của <strong>Aksara CMS</strong> và bắt đầu xây dựng nền tảng của riêng bạn mà không có giới hạn.",
        'GET SOURCE CODE': "NHẬN MÃ NGUỒN",
    },
    'th': {
        'GET STARTED': "เริ่มต้นใช้งาน",
        'Trusted by Organizations and Enterprises': "ได้รับความไว้วางใจจากองค์กรและธุรกิจต่างๆ",
        'Community &amp; Engagement': "ชุมชนและการมีส่วนร่วม",
        'Daily Visits': "การเข้าชมรายวัน",
        'Unique visitors today.': "ผู้เข้าชมใหม่วันนี้",
        'Weekly Visits': "การเข้าชมรายสัปดาห์",
        'Total visits this week.': "ยอดเข้าชมสัปดาห์นี้",
        'Monthly Visits': "การเข้าชมรายเดือน",
        'Total visits this month.': "ยอดเข้าชมเดือนนี้",
        'Yearly Visits': "การเข้าชมรายปี",
        'Total visits this year.': "ยอดเข้าชมปีนี้",
        'Published Articles': "บทความที่เผยแพร่",
        'Total content available.': "เนื้อหาทั้งหมดที่มีอยู่",
        'Interactions': "การโต้ตอบ",
        'User comments &amp; feedback.': "ความคิดเห็นและคำติชมของผู้ใช้",
        'Featured Galleries': "แกลเลอรี่ที่นำเสนอ",
        'See all galleries': "ดูแกลเลอรี่ทั้งหมด",
        'Latest news': "ข่าวล่าสุด",
        'See all news': "ดูข่าวทั้งหมด",
        'Build Your Application Today': "สร้างแอปพลิเคชันของคุณวันนี้",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "รับซอร์สโค้ดฉบับเต็มของ <strong>Aksara CMS</strong> และเริ่มสร้างแพลตฟอร์มของคุณเองโดยไม่มีข้อจำกัด",
        'GET SOURCE CODE': "รับซอร์สโค้ด",
    },
    'ja': {
        'GET STARTED': "今すぐ始める",
        'Trusted by Organizations and Enterprises': "組織や企業からの信頼",
        'Community &amp; Engagement': "コミュニティとエンゲージメント",
        'Daily Visits': "今日の訪問者",
        'Unique visitors today.': "本日のユニーク訪問者。",
        'Weekly Visits': "今週の訪問者",
        'Total visits this week.': "今週の総訪問数。",
        'Monthly Visits': "今月の訪問者",
        'Total visits this month.': "今月の総訪問数。",
        'Yearly Visits': "今年の訪問者",
        'Total visits this year.': "今年の総訪問数。",
        'Published Articles': "公開された記事",
        'Total content available.': "利用可能なコンテンツの合計。",
        'Interactions': "インタラクション",
        'User comments &amp; feedback.': "ユーザーのコメントとフィードバック。",
        'Featured Galleries': "注目のギャラリー",
        'See all galleries': "すべてのギャラリーを見る",
        'Latest news': "最新ニュース",
        'See all news': "すべてのニュースを見る",
        'Build Your Application Today': "今すぐアプリケーションを構築しましょう",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "<strong>Aksara CMS</strong>の完全なソースコードを入手して、制限なしで独自のプラットフォームの構築を開始してください。",
        'GET SOURCE CODE': "ソースコードを入手",
    },
    'ko': {
        'GET STARTED': "시작하기",
        'Trusted by Organizations and Enterprises': "조직 및 기업의 신뢰",
        'Community &amp; Engagement': "커뮤니티 및 참여",
        'Daily Visits': "일일 방문",
        'Unique visitors today.': "오늘 고유 방문자.",
        'Weekly Visits': "주간 방문",
        'Total visits this week.': "이번 주 총 방문 수.",
        'Monthly Visits': "월간 방문",
        'Total visits this month.': "이번 달 총 방문 수.",
        'Yearly Visits': "연간 방문",
        'Total visits this year.': "올해 총 방문 수.",
        'Published Articles': "게시된 기사",
        'Total content available.': "사용 가능한 총 콘텐츠.",
        'Interactions': "상호 작용",
        'User comments &amp; feedback.': "사용자 댓글 및 피드백.",
        'Featured Galleries': "주요 갤러리",
        'See all galleries': "모든 갤러리 보기",
        'Latest news': "최신 뉴스",
        'See all news': "모든 뉴스 보기",
        'Build Your Application Today': "지금 바로 애플리케이션을 구축하세요",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "<strong>Aksara CMS</strong>의 전체 소스 코드를 받아 제한 없이 나만의 플랫폼을 구축하세요.",
        'GET SOURCE CODE': "소스 코드 받기",
    },
    'zh': {
        'GET STARTED': "开始使用",
        'Trusted by Organizations and Enterprises': "受组织和企业信赖",
        'Community &amp; Engagement': "社区与参与",
        'Daily Visits': "每日访问",
        'Unique visitors today.': "今日独立访客。",
        'Weekly Visits': "每周访问",
        'Total visits this week.': "本周总访问量。",
        'Monthly Visits': "每月访问",
        'Total visits this month.': "本月总访问量。",
        'Yearly Visits': "每年访问",
        'Total visits this year.': "今年总访问量。",
        'Published Articles': "已发表文章",
        'Total content available.': "可用内容总量。",
        'Interactions': "互动",
        'User comments &amp; feedback.': "用户评论和反馈。",
        'Featured Galleries': "精选画廊",
        'See all galleries': "查看所有画廊",
        'Latest news': "最新新闻",
        'See all news': "查看所有新闻",
        'Build Your Application Today': "立即构建您的应用程序",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "获取 <strong>Aksara CMS</strong> 的完整源代码，开始无限制地构建您自己的平台。",
        'GET SOURCE CODE': "获取源代码",
    },
    'ar': {
        'GET STARTED': "ابدأ الآن",
        'Trusted by Organizations and Enterprises': "موثوق به من قبل المنظمات والشركات",
        'Community &amp; Engagement': "المجتمع والمشاركة",
        'Daily Visits': "الزيارات اليومية",
        'Unique visitors today.': "الزوار الفريدون اليوم.",
        'Weekly Visits': "الزيارات الأسبوعية",
        'Total visits this week.': "إجمالي الزيارات هذا الأسبوع.",
        'Monthly Visits': "الزيارات الشهرية",
        'Total visits this month.': "إجمالي الزيارات هذا الشهر.",
        'Yearly Visits': "الزيارات السنوية",
        'Total visits this year.': "إجمالي الزيارات هذا العام.",
        'Published Articles': "المقالات المنشورة",
        'Total content available.': "إجمالي المحتوى المتاح.",
        'Interactions': "التفاعلات",
        'User comments &amp; feedback.': "تعليقات وملاحظات المستخدمين.",
        'Featured Galleries': "المعارض المميزة",
        'See all galleries': "عرض جميع المعارض",
        'Latest news': "أحدث الأخبار",
        'See all news': "عرض جميع الأخبار",
        'Build Your Application Today': "ابنِ تطبيقك اليوم",
        'Get the complete source code of <strong>Aksara CMS</strong> and start building your own platform without limitations.': "احصل على الكود المصدري الكامل لـ <strong>Aksara CMS</strong> وابدأ في بناء منصتك الخاصة دون قيود.",
        'GET SOURCE CODE': "احصل على الكود المصدري",
    },
}

for lang, mapping in translations.items():
    lang_dir = os.path.join(base_dir, lang)
    os.makedirs(lang_dir, exist_ok=True)

    new_content = source
    for original, translated in mapping.items():
        new_content = new_content.replace(original, translated)

    lang_index = os.path.join(lang_dir, 'index.php')
    with open(lang_index, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"[OK] {lang}/index.php")

print("\nDone!")
